# Generated by Django 2.2.1 on 2019-05-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogtype',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
