# Generated by Django 2.2.1 on 2019-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190530_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-createTime']},
        ),
    ]
